# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\_Prj\FileSort\gui/CustomEnter.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetId(object):
    def setupUi(self, SetId):
        SetId.setObjectName("SetId")
        SetId.resize(428, 41)
        SetId.setSizeGripEnabled(True)
        SetId.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SetId)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtId = QtWidgets.QLineEdit(SetId)
        self.txtId.setMaxLength(3000)
        self.txtId.setObjectName("txtId")
        self.horizontalLayout.addWidget(self.txtId)
        self.btnOk = QtWidgets.QDialogButtonBox(SetId)
        self.btnOk.setOrientation(QtCore.Qt.Horizontal)
        self.btnOk.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout.addWidget(self.btnOk)
        self.horizontalLayout.setStretch(0, 1)

        self.retranslateUi(SetId)
        self.btnOk.accepted.connect(SetId.accept)
        QtCore.QMetaObject.connectSlotsByName(SetId)

    def retranslateUi(self, SetId):
        _translate = QtCore.QCoreApplication.translate
        SetId.setWindowTitle(_translate("SetId", "Enter"))
